Sprint 2/step 2
anton-iavorskii/react-burger pull request #3
Opened 2023-01-30 12:47 UTC by anton-iavorskii

2023-01-30 16:07 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлению DnD и Redux в ваш проект, отлично применяете хуки для оптимизации производительности, реализовали переключение в навигации по ингредиентам, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Т.к. в конструкторе присутствуют 2 булки, то следует выставить аналогичное значение в списке ингредиентов в счётчике и добавить в конец массива заказа идентификатор булки;
- Отсутствует возможность перенести повторно ингредиент, который уже перенесли;
- Состояние хранилища следует разбить на следующие элементы (редьюсеры) и вынести каждый из них в отдельный файл:
    - список всех полученных ингредиентов,
    - список всех ингредиентов в текущем конструкторе бургера,
    - объект текущего просматриваемого ингредиента,
    - объект созданного заказа.
- Не следует переносить состояния, которые используются только в рамках одного компонента в хранилище, это усложняет проект и контроль за кодом. Для переключения табов следует использовать классический `useState`;
- В качестве ключа для элемента в конструкторе не следует использовать индекс, генерируйте уникальное значение с использованием подходящей библиотеки, например `uuid` для оптимизации производительности в рамках ре-рендера;

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-01-30 16:07 UTC, randomroot commented on package.json
> +    "@reduxjs/toolkit": "^1.9.1",
🟡 **Можно улучшить:**

Данная библиотека не используется в рамках проекта, поэтому её можно безопасно убрать из списка зависимостей для экономии памяти

2023-01-30 16:07 UTC, randomroot commented on src/services/reducers/ingredients.js
> +export const tabsReducer = (state = tabsInitialState, action) => {
🔴 **Нужно исправить:**

Не следует переносить состояния, которые используются только в рамках одного компонента в хранилище, это усложняет проект и контроль за кодом. Для переключения табов следует использовать классический `useState`

2023-01-30 16:07 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +  const onDropHandler = (itemId) => {
🟡 **Можно улучшить:**

Т.к. функция используется всего один раз в рамках файла и состоит из одной строки, то можно перенести код непосредственно в `drop` выше :)

2023-01-30 16:07 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    constructorItems.forEach((item) => {
🟡 **Можно улучшить:**

Можно заменить на функцию `reduce` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2023-01-30 16:07 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +    return constructorItems.find((item) => item.type === 'bun');
🟡 **Можно улучшить:**

Имеет смысл вынести значение булки в отдельную переменную в рамках состояния, чтобы удобно её заменять и сразу получать, не используя поиск по массиву. Это улучшит скорость приложения

2023-01-30 16:07 UTC, randomroot commented on src/components/burger-ingredients/burger-ingredients.jsx
> +          <div ref={refBunsContainer}>
🟡 **Можно улучшить:**

Имеет смысл вынести категорию ингредиентов в отдельный компонент, чтобы уменьшить дублирование кода

2023-01-30 16:07 UTC, randomroot commented on src/services/reducers/ingredients.js
> +        ingredient: [...state.items].find((item) => item._id === action.id),
🔴 **Нужно исправить:**

**Здесь и ниже аналогично:**
В данном случае копия исходного массива не требуется, т.к. он не изменяется в ходе данного экшена

2023-01-30 16:07 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +          <ConstructorCard key={index} item={item} index={index} />
🔴 **Нужно исправить:**

В качестве ключа не следует использовать индекс, генерируйте уникальный ключ например на основе библиотеки `uuid`, чтобы оптимизировать ререндеринг.

Генерацию ключа следует делать в рамках отдельной action creator функции, в момент добавления ингредиента в конструктор

2023-01-30 16:07 UTC, randomroot commented on src/components/constructor-card/constructor-card.jsx
> +  const handlerDelete = () => {
🟡 **Можно улучшить:**

Возможно, здесь есть орфографическая ошибка, названия функций следует приводить к виду "действие"

2023-01-30 16:07 UTC, randomroot commented on src/components/constructor-card/constructor-card.jsx
> +    >
🟡 **Можно улучшить:**

При перетаскивании элементов целесообразно визуально показать процесс перетаскивания, с помощью изменения `opacity` данного элемента

2023-01-30 16:07 UTC, randomroot commented on src/components/constructor-card/constructor-card.jsx
> +      key={item._id}
🔴 **Нужно исправить:**

Следует убрать данный атрибут из `div`, т.к. он блокирует повторный перенос ингредиента в конструкторе

2023-02-01 09:24 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- Каждый редьюсер следует выделить **в отдельный файл;**
- Следует **разделить** редьюсер ингредиентов на два - один отвечающий за получение и хранение ингредиентов с сервера, а второй - за конструктор заказа;
- Следует **выделить** в отдельный редьюсер всё, что связано с процессом создания заказа: отправку и получения информации о заказе с выводом в модальное окно;
- В качестве **ключа** для элемента в конструкторе **не следует использовать идентификатор ингредиента** `_id`, так как в конструкторе могут присутствовать несколько копий одного и того же ингредиента. Генерируйте **уникальное** значение с использованием подходящей библиотеки, например `uuid` для оптимизации производительности в рамках ре-рендера, на этапе добавления в конструктор (в функции _action-creator_-a).

**Хорошего вам дня и настроения!** 🐈

2023-02-01 09:24 UTC, randomroot commented on src/components/burger-constructor/burger-constructor.jsx
> +          <ConstructorCard key={item._id} item={item} index={index} />
🔴 **Нужно исправить:**

В конструкторе может присутствовать несколько одинаковых ингредиентов, поэтому идентификаторы карточек могут совпасть и произойдет лишний рендер. Следует самостоятельно создать уникальные значения для каждого ингредиента, **добавленного в конструктор**

2023-02-01 09:46 UTC, anton-iavorskii commented
Спасибо за ОС! Но мне не очень понятно, как я могу разделить редьюсер, если по логике в редьюсерах, которые будут отвечать за конструктор и заказ мне нужно использовать state редьюсера, который хранит все ингредиенты? Ведь два редьюсера не могут использвать один и тот же state или я ошибаюсь?

2023-02-01 10:02 UTC, randomroot commented
@anton-iavorskii 

Смотрите, в момент создания заказа в `burger-constructor` вы получаете из редьюсера **конструктора** набор ваших ингредиентов, преобразуете их в массив идентификаторов, а затем этот набор передаете в функцию `getOrder`, которая уже вызывает диспатч экшенов, которые лежат в редьюсере **заказа**. То есть, редьюсер заказа будет отвечать именно за экшены `GET_ORDER_REQUEST`, `GET_ORDER_SUCCESS` и `GET_ORDER_FAILED`.

2023-02-01 10:14 UTC, anton-iavorskii commented
Спасибо! С заказом понятно. Но больший вопрос вызывает как мне использовать в редьюсере конструктора стейт редьюсера ингредиентов. Ведь у меня прописана такая логика: при добавлении в конструктор элемента я по id ищу объект во всех ингредиентах (то есть здесь мне как раз и нужно состояние другого редьюсера) и записываю его в ингредиенты конструктора. Или я не правильно делаю?

2023-02-01 10:42 UTC, randomroot commented
@anton-iavorskii 

В этом случае можно упростить процесс переноса, если вместо идентификатора заказа передавать целиком копию объекта ингредиента - тогда в конструкторе при `onDrop` все нужные данные уже будут готовы к добавлению в другой редьюсер, останется только добавить `id`.
Либо, вы можете создать отдельный action creator, внутри которого вы сможете получить нужные данные из другого редюсера по `id` (см. https://stackoverflow.com/a/35674575):

2023-02-01 10:55 UTC, anton-iavorskii commented
Спасибо большое! Все понял, затупил немного.

2023-02-01 15:36 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

В качестве дополнительной **рекомендации** предлагаю вам рассмотреть **сброс редьюсеров** заказа и выбранного ингредиента после закрытия модального окна, чтобы сэкономить память и случайно не отобразить предыдущие значения, до установки новых :)

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-01 15:44 UTC, anton-iavorskii commented
Благодарю за комментарии, они были очень полезны!

2023-04-10 17:10 UTC, merged