sprint-5/step-1
anton-iavorskii/react-burger pull request #6
Opened 2023-05-22 06:14 UTC by anton-iavorskii

2023-05-22 07:02 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Реализована страница ленты заказов;

### **Но есть несколько замечаний, которые нужно исправить:**

- У вас не закрывается сокет соединение, когда пользователь уходит со страницы `/feed` и `/profile/orders`. По чек-листу: Сокет-соединение открывается, когда пользователь переходит на экраны «Лента заказов» или «История заказов», и закрывается, когда пользователь покидает их. <https://disk.yandex.com/i/x2TYrPJ2d95hUA> - это можно проверить в девтулс, во вкладке `networks`.

- При открытии/закрытии модального окна на страницах `/feed` и `/profile/orders`, у вас каждый раз заново открывается сокет соединение. Соединение должно открываться только 1 раз (когда пользователь зашёл на страницу) и закрываться, когда пользователь ушёл соо страницы.

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали);

- <https://disk.yandex.com/i/fpo8X6CB84Cmgw> - когда у пользователя нет заказов не нужно отображать контент из ленты заказов.

- <https://disk.yandex.com/i/uFQxVc1iwo-8Nw> - В сокет соединение `/orders`, вы передаёте токен с `Bearer`, именно поэтому у пользователя не отображаются его заказы.

### **Сделает код лучше:**

- <https://disk.yandex.com/i/EKGbkCBAlaGUHg> - тут лучше сделать такой же вид, как и тут: <https://disk.yandex.com/i/EoQcJUPzQA-z-g>;

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

### **После исправления всех замечаний, работа будет принята)**

2023-05-22 07:02 UTC, ArslanMustafin commented on src/index.tsx
> +};
**Можно лучше:**

лучше вынести в отдельный файл с другими экшенами)

2023-05-22 07:02 UTC, ArslanMustafin commented on src/services/actions/ingredients.ts
> +}
**Надо исправить:**

Здесь вы тоже должны использовать `fetchWithRefresh`, а также передавать `accessToken`.

2023-05-22 07:02 UTC, ArslanMustafin commented on src/pages/profile-orders/profile-orders.tsx
> +      payload: WS_BASE_URL + "?token=" + localStorage.getItem("accessToken"),
**Надо исправить:**

Тут нужно передавать `accessToken` бее приписки `Bearer`)

2023-05-22 07:02 UTC, ArslanMustafin commented on src/pages/profile-orders/profile-orders.tsx
> +          style={{ width: "99%" }}
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданных классов. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2023-05-22 07:02 UTC, ArslanMustafin commented on src/pages/profile/profile.tsx
> +} | null;
**Можно лучше:**

Вы ведь задаёте начальное значение для формы, почему она может быть `null`?

2023-05-22 07:02 UTC, ArslanMustafin commented on src/pages/profile/profile.tsx
> +              value={values?.email}
**Надо исправить:**

Здесь и далее.

ts правильно ругается)) вам нужно дать ему понять, что email это строка)

можно написать вот так:

`value={values?.email as string}`

Но это лучше делать только в том случае если вы на 100% уверены что это будет так.

2023-05-22 07:02 UTC, ArslanMustafin commented on src/services/actions/user.ts
> +        // @ts-ignore
**Надо исправить:**

Здесь и далее.

вам нужно убрать `ts-ignore`.

Важно следить за типами, тс не будет ругаться просто так, попросите помощи у наставника, тут можно спокойно обойтись без @ts-ignore.

2023-05-24 06:10 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- Было бы круто сделать loader, когда пользователь отправляет заказ, чтобы было понятно, идёт отправка заказа;

2023-05-24 06:12 UTC, anton-iavorskii commented
Cпасибо за ревью! Лоадер доделаю)

2023-05-24 06:23 UTC, merged